GET http://localhost:8080/user/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIwN2FiYmNkOS1jYmY1LTQyNDQtODIyYi02NzA4MTcwY2VjZDAiLCJpYXQiOjE2OTMyMTYxMzUsImV4cCI6MTY5NDA4MDEzNX0.qltcTT4JI6yo8kq0WBX3ZF2ldCWFMFdyTmo3wGy_3hVIV02xTcslxleeFFGzK2RR_sY3Fy24x-mcMhwwdE1pRw

###
GET http://localhost:8080/auth/hello
